### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Shorey-Git** [8084/switch-to-audible-tab#3]
hi klntsky, 
Your 'Switch to Audible' tab software plugin is great and I use it all the time , Thankyou for making it .

One request and maybe it would be a separate plugin but based on mostly the same code/concept, it is to have a 'mute all other tabs' so you could switch to the one you want (via Switch to Audible Tab) and then press 'mute all others', and maybe it could have a 'follow mode' option where it mutes the tab as you leave and unmutes the new 'current tab'. 
Thankyou

**Comment by klntsky** [comment]
Hi and sorry for delayed response.

I think it may be a useful feature to have for someone, but not for this extension (its name suggests the primary use case).

Personally, I wouldn't use such a feature, because muting other tabs via the browser tabs API is too wasteful - the sound would still keep playing in the tab context and occupy network resources. There is no general way to click the "pause" player button on any website to stop the sound and not just mute, so I guess it's impossible or very hard to implement it properly.

**Comment by klntsky** [comment]
I just found an extension that implements the second part of your idea: https://addons.mozilla.org/en-US/firefox/addon/mute-unfocused-tabs/

**Comment by Shorey-Git** [comment]
Thankyou very much klntsky.
and thankyou for the suggestion of the other app. I will try that
